// Autogenerated by: configuration-parser.py
// Guards:
#ifndef __CRYPTOGRAPHY_CONSTANTS_HPP__
#define __CRYPTOGRAPHY_CONSTANTS_HPP__


// Constants:
extern unsigned char AES_ENCRYPTION_KEY[32];
extern unsigned int AES_ENCRYPTION_KEY_length;

extern unsigned char NONCE[12];
extern unsigned int NONCE_length;

// Guard:
#endif /** __CRYPTOGRAPHY_CONSTANTS_HPP__ */